<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",487,519);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",1005,1040);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel"," \r\n<li><a id=\"main1-l2li\" href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n",1497,1616);
$z[6][4]['type']="son";
$z[7]=Array("type","[field:typename/]",3347,3387);
$z[8]=Array("field","",3428,3457);
$z[8][4]['name']="position";
$z[9]=Array("field","",3518,3539);
$z[9][4]['name']="content";
$z[10]=Array("include","",3617,3654);
$z[10][4]['filename']="footer.htm";

?>