<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",342,371);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",411,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",487,519);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",1611,1646);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",4886,4915);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n		 <div class=\"list-r-1\">\r\n            <h1><a href=\"[field:arcurl/]\">[field:title/]</a></h1>\r\n            <p>[field:description/]...<a href=\"[field:arcurl/]\">[ÏêÏ¸]</a></p>\r\n         </div>\r\n	",4978,5210);
$z[7][4]['pagesize']="20";
$z[8]=Array("pagelist","",5266,5337);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",5817,5854);
$z[9][4]['filename']="footer.htm";

?>